export const REQUEST_CITY_WEATHER = 'REQUEST_CITY_WEATHER'
export const RECEIVE_CITY_WEATHER = 'RECEIVE_CITY_WEATHER'
export const ERROR_CITY_WEATHER = 'ERROR_CITY_WEATHER'

export const UPDATE_INPUT_CITY = 'UPDATE_INPUT_CITY'
export const RESET_INPUT_CITY = 'RESET_INPUT_CITY'
